### ISSUE TITLE
Add Account and Environnement attributes to Workflow Run

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/jarvis-manager#10]
For any Workflow Runs, their is no Account and Environnement attributes. 

Add this information to the json run.

Needed to filter the workflow runs regarding the users

**Comment by julienguarino** [comment]
This issue will be processed in the legacy repository under GCP.

**Comment by julienguarino** [comment]
Impacted DAGs

- gbq-to-gbq
- storage-to-tables
- storage-to-storage

**Comment by julienguarino** [comment]
Pushed to PRODUCTION
