### ISSUE TITLE
jarvis create configuration help

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/jarvis-manager#14]
The `jarvis create configuration help` doesn't present all the configuration types that could be created by the SDK.

**Comment by julienguarino** [comment]
The command "jarvis create configuration create" now display the following info :

Jarvis Configuration manager HELP
---------------------------------

Usage: jarvis create CONFIGURATION_TYPE [output_filename.json]

This command will create a file with the specified CONFIGURATION_TYPE template.

Available CONFIGURATION_TYPE:

* storage-to-storage
* storage-to-table
* table-to-storage

Note that if you do not specify an output filename, the generated file will be created in the current directory and named : CONFIGURATION_TYPE.json
