### ISSUE TITLE
Tailer Monitoring API : Improve the json parameters to call API for TTT configuration

### ISSUE THREAD

**Issue by romone22** [Jarvis-Platform/jarvis-manager#53]
Currently, to call the monitoring API for a TTT configuration, we need to : 
- use set the configuration type to gbq_to_gbq
- add the environment at the name of the configuration_id

Example of a current payload to call the API for a TTT configuration : 
```
TAILER_API_JWT=`python3 google-jwt-generator.py your-credentials.json` \
&& curl --request POST \
--http2 \
--header "content-type:application/json" \
--header "Authorization: Bearer ${TAILER_API_JWT}" \
--data '{ "action": "launch_job",
          "account": "000099",
          "environment": "DEV",
          "configuration_type": "gbq-to-gbq",
          "configuration_id": "000099_iowa_liquor_prepare_pda_DEV",
          "job_id": "gbq-to-gbq|000099_iowa_liquor_prepare_pda_DEV"}' \
"https://tailer-api-nqonovswsq-ew.a.run.app/v1/dag/launch" 
```

The updated payload to call the APIs should be : 
```
TAILER_API_JWT=`python3 google-jwt-generator.py your-credentials.json` \
&& curl --request POST \
--http2 \
--header "content-type:application/json" \
--header "Authorization: Bearer ${TAILER_API_JWT}" \
--data '{ "action": "launch_job",
          "account": "000099",
          "environment": "DEV",
          "configuration_type": "table-to-table",
          "configuration_id": "000099_iowa_liquor_prepare_pda"}' \
"https://tailer-api-nqonovswsq-ew.a.run.app/v1/dag/launch" 
```
In summary : 
- replace gbq-to-gbq by table-to-table
- suppress the job_id entry
- Later, suppress the environment extension

**Comment by julienguarino** [comment]
- replace gbq-to-gbq by table-to-table : implemented, tested, deployed to production
- suppress the job_id entry :  implemented, tested, deployed to production
- Later, suppress the environment extension : implemented, tested, NOT DEPLOYED TO PROD YET

**Comment by romone22** [comment]
Documentation on Gitbook updated and Monitoring example in the demo repo updated
